name: global_dialog
description: A simple package to get you started with dialog interactions from your business logic
version: 0.1.0
homepage: https://github.com/leam-tech/global_dialog.dart

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
