name: global_dialog
description: A simple package to get you started with dialog interactions from your business logic
version: 0.2.0
homepage: https://github.com/leam-tech/global_dialog

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
